# Generated by Django 4.0.6 on 2022-07-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '2. Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '1. Brand'},
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm1.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm1.category')),
            ],
            options={
                'verbose_name_plural': '3. Products',
            },
        ),
    ]
