# Generated by Django 4.0.6 on 2022-07-26 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0002_category_alter_brand_options_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=15)),
                ('color_title', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '4.Colors',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': '5.Sizes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Productattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm1.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm1.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm1.sizes')),
            ],
            options={
                'verbose_name_plural': '6.Product Attributes',
            },
        ),
    ]
