# Generated by Django 4.0.6 on 2022-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0003_color_sizes_product_status_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFeatured',
            field=models.BooleanField(default=True),
        ),
    ]
