# Generated by Django 4.0.6 on 2022-07-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0004_product_isfeatured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_id',
            new_name='color_code',
        ),
    ]
