# Generated by Django 4.0.6 on 2022-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0006_alter_color_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(default='/n', max_length=400),
        ),
    ]
