# Generated by Django 4.0.6 on 2022-07-27 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comm1', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='comm1.category'),
        ),
    ]
